# describe rust in python

def myfunc_return_first_char(s: str) -> int: ...
def sum_as_string(a:int, b:int) -> int: ...
class DummyClass:
    @staticmethod
    def get_42(self) -> int: ...

fourtytwo: int